spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dbAppTravel?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
        username: root
        password: 123456
    
    jpa:
        show-sql: true